server:
  port: 9001
logging:
  level:
    root: warn
    pers.fjl.server: debug
  file:
    path: log/blog-dev.log
spring:
  mail:
    host: smtp.qq.com #我用的是qq，用其他的也是一样
    username: 1484908116@qq.com #这个是qq邮箱
    password: lxffxabqpbsoffda #注意这个不是密码，是客户端授权码
    default-encoding: UTF-8 #这个是字符集,咱们用utf-8就可以了

  application:
    name: blog-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml